Develop stage 2
k-karuna/airbnb-demo-frontend pull request #2
Opened 2017-11-17 07:54 UTC by k-karuna

https://build-xvtggmoept.now.sh/

2017-11-17 12:30 UTC, evgenyrodionov commented
Бордер у хедера не тот
![image](https://user-images.githubusercontent.com/775692/32947265-283880fe-cbac-11e7-9001-efdc91bbcea0.png)

Шрифт у See all
![image](https://user-images.githubusercontent.com/775692/32947274-2f55c8f6-cbac-11e7-87fd-3adecb0d6b2d.png)

Бордеры в футере и отступы и шрифты тоже не те
![image](https://user-images.githubusercontent.com/775692/32947284-37abb43e-cbac-11e7-8b81-7ee2dcba3fa6.png)

Тут тоже бордеры не те + между карточками не тот отступ
![image](https://user-images.githubusercontent.com/775692/32947300-45105dfa-cbac-11e7-96e6-4f17e26393a6.png)

2017-11-17 12:30 UTC, evgenyrodionov commented
Используй реакт-роутеровский Линк

2017-11-17 12:31 UTC, evgenyrodionov commented
Название ПРа не отражает **сделанную** работу

2017-11-17 22:37 UTC, k-karuna commented
https://build-nyvhritggh.now.sh/

2017-11-18 08:43 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/32978548-94ea3b76-cc55-11e7-9854-f917c1eb07df.png)
![image](https://user-images.githubusercontent.com/775692/32978549-9740f036-cc55-11e7-8bfa-0faa68bd12cf.png)

2017-11-18 08:44 UTC, evgenyrodionov commented
Отступы между карточками слишком большие, мне кажется
![image](https://user-images.githubusercontent.com/775692/32978563-c74e8798-cc55-11e7-926b-b2824a01f705.png)

2017-11-18 08:50 UTC, imevro requested changes

2017-11-18 08:50 UTC, evgenyrodionov commented on src/Header/styled.js
> +  position: absolute;
фу, зачем?

2017-11-18 08:50 UTC, evgenyrodionov commented on src/Header/styled.js
> +  @media only screen and (min-width: 992px) {
медиакверис объявляются позже основных правил

2017-11-18 08:50 UTC, evgenyrodionov commented on src/Homes/Filters.js
> +    return;
убери нулевой return, это зло, лучше просто пустой метод оставь

2017-11-18 08:50 UTC, evgenyrodionov commented on src/Homes/Filters.js
> +    this.state.isOpen
можно проще: `this.setState({ isOpen: !this.state.isOpen })`

2017-11-18 08:50 UTC, evgenyrodionov commented on src/Homes/Filters.js
> +        <div className="row">
а зачем тебе роу, если ты не используешь колонки?

2017-11-18 08:50 UTC, evgenyrodionov commented on src/Homes/Homes.js
> +const GMapCenterCoord = { lat: 50.01038826014866, lng: -118.6525866875 };
4 знака после точки достаточно

2017-11-18 08:50 UTC, evgenyrodionov commented on src/Homes/Homes.js
> +              <div className="col-md-4 col-sm-6 col-xs-12 col-12">
от меньшего к большему, а то у тебя трешак `col-xs-12 col-sm-6 col-md-5`

и что такое col-12?

2017-11-18 08:50 UTC, evgenyrodionov commented on src/Homes/Homes.js
> +                    dollars="82"
price и передавай числом

2017-11-18 08:50 UTC, evgenyrodionov commented on src/Homes/HomesFooter.js
> +          </FooterText>
ты и так в футере, зачем эти префиксы

2017-11-18 20:17 UTC, k-karuna commented
Зафиксил, новый билд:
https://build-izgsefnstc.now.sh/

2017-11-20 08:58 UTC, imevro requested changes

2017-11-20 08:58 UTC, evgenyrodionov commented on src/Grid.css
> +@media (min-width: 0px) {
а зачем?

2017-11-20 08:58 UTC, evgenyrodionov commented on src/index.css
> +  outline: 0;
outlinenone.com

2017-11-21 07:52 UTC, k-karuna commented
Пофиксил замечания

2017-11-21 09:22 UTC, imevro approved these changes

2017-11-21 09:25 UTC, merged